#!/bin/bash

export OS=$(uname -s)

function banner () {
    echo -e "\n= $1 ======================================"
}


install_package() {
    package=$1
    # echo "package to install: $package"
    if ! command -v $package &> /dev/null; then
        echo "Package '$package' not installed. Installing..."
        if command -v apt &> /dev/null; then
            sudo apt update
                sudo apt install -y "$package"
            elif command -v brew &> /dev/null; then
            brew install "$package"
        else
            echo "Package manager not found. Please install '$package' manually."
        fi
    fi
}

install_pyenv() {
    banner "install pyenv"

    if command -v pyenv &> /dev/null; then
        echo "pyenv already installed."
    else
        echo "installing pyenv."
        if [[ "$OS" == "Darwin" ]]; then
            brew install pyenv
        elif [[ "$OS" == "Linux" ]]; then
            curl -fsSL https://pyenv.run | bash
            rehash
        else
            echo "Unknown OS"
        fi
    fi
}

install_emacs() {
    banner "install emacs"

    install_package emacs

    # install spacemacs
    if [[ ! -d ~/.emacs.d ]]; then
        mkdir -p ~/.emacs.d || { echo "Failed to create ~/.emacs.d"; exit 1; }
        git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d || { echo "Failed to clone Spacemacs"; rm -rf ~/.emacs.d; exit 1; }
    else
        echo "~/.emacs.d already exists. skipping any spacemacs updates."
    fi
}

install_eza() {
    banner "install eza"
    if command -v eza &> /dev/null; then
        echo "eza already installed."
    else
        echo "installing eza."
        if [[ "$OS" == "Darwin" ]]; then
            brew install eza
        elif [[ "$OS" == "Linux" ]]; then
            sudo apt update
            sudo apt install -y gpg
            sudo mkdir -p /etc/apt/keyrings
            wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
            echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
            sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
            sudo apt update
            sudo apt install -y eza
            rehash
        else
            echo "Unknown OS"
        fi
    fi
}

install_pyenv
install_emacs
install_eza
